

services:
  backend:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    container_name: django-server
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine
    container_name: redis-server


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amazon

    
  celery:
    image: celery:4.0.2
    container_name: celeryserver
    build: .
    volumes:
      - .:/app
    command: celery -A project worker -l INFO
    depends_on:
      - backend


volumes:
  postgres_data: